# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dabbd80005ce41770c876322cb550caa27ea7250dd7a6ab1f3e81189533111fb8fcb2090ff161357189da6573b72b09a623218a67dfc5d983c284a452e98581e

test:
  secret_key_base: b3d5b4008e712c872e9420e6e863e767dbb53ce43313ca5aa0b74ec627f3c2ac8922cc8a0064d05b04a1cb5142880e0d87d321a5bd55efb4dd6cf2a3329fcba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
